### ISSUE TITLE
[Webinterface] Recommend to the user a safe gas price for their PRL transaction

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/webinterface#116]
If the user doesn't use enough gas for their PRL payment it could take a long time to go through.  On the screen where we tell them the amount of PRL to pay and the ETH address to send it to, we should also tell them a safe gas price.  

There are several APIs out there we could query for this information.  Select one that is reliable and consistently available.  

Taylor has updated the mockups:
https://framer.cloud/ahwhK

edit: Use a fallback gas price in case the api is down.

**Comment by jfarago** [comment]
Also include a fallback gas price in case the API is down.

**Comment by jfarago** [comment]
I'm not finding many API's, but I might not be searching correctly. 

[Eth Gas Station](https://ethgasstation.info/gasrecs.php) - [api request](https://ethgasstation.info/json/ethgasAPI.json) - Very slow(7 seconds) but i see this referenced more
[Block Cypher](https://www.blockcypher.com/dev/ethereum/#blockchain-api) - [api request](https://api.blockcypher.com/v1/eth/main) - im not sure what unit the gas price is in on this request

At this point i recommend using Eth Gas Station

**Comment by jfarago** [comment]
Decided to go with Block Cypher because the gas station was too slow.
