### ISSUE TITLE
[Webinterface] Sometimes downloads are scrambled

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/webinterface#118]
![image.png](https://images.zenhubusercontent.com/5a8c55194b5806bc2bc7ac81/05834510-373f-4e8a-bdc3-9f7acbc58517)

Handle:  dog2.pnge4e2f4bb4225ec6f3955f1984b61cb8c896a8714d0c93ae03bdddd855a20006aoa5qjqsm

This doesn't always happen, but from time to time I've noticed downloads seem scrambled.  This seems to be an issue only very recently and I haven't figured out yet whether it's a broker or webinterface issue.

**Comment by Alisamix** [comment]
This was an issue in the first testnet already - not sure why this happens though.

**Comment by rfornea** [comment]
Meant to post this here, but forgot.  I think this is caused by the treasure chunk--webinterface is able to decrypt it for some reason, it doesn't come back "" or NULL like we'd thought it would.  I'll add something into #109 that will fix this as well.

**Comment by rfornea** [comment]
@automyr   In order to fix this, I was planning on adding a chunk prefix to the file chunks that the webinterface could check for when it decrypts, much like the treasure prefix that I add to the treasure payloads on the brokernode that the webnode uses to figure out which chunks are treasure.  

Are there any problems with this approach?  Jet mentioned using the tag was also an option.

**Comment by automyr** [comment]
I think this approach is fine, just append something like "chunk:" or "filedata:" in bytes at the start of the plaintext before passing it through AES. 

Beware the [Birthday Paradox](https://en.wikipedia.org/wiki/Birthday_problem) though, as if the bytestring that we're trying to match is too short, there's a possibility (and not as small as you'd think) that the starting bytes of a wrongly-decrypted ciphertext match our "tag".

**Comment by rfornea** [comment]
I guess a solution to reduce this possibility would be making the prefix as long as possible while still getting 1 kb of data in the chunks?

**Comment by automyr** [comment]
That works. We don't need to go too crazy, something 32 bytes long is more than enough to never (never say never, but the probability does approach zero) have to worry about this, and we have more than enough space to accommodate this in one chunk.

**Comment by nullpilot** [comment]
This should be fixed with the gcm-authed chunks.

**Comment by rfornea** [comment]
This issue was actually fixed when I implemented the prefixes, but I marked the issue as "done" rather than closing it.
