### ISSUE TITLE
[Webinterface] Do something when paymentStatus comes back as error 

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/webinterface#125]
We can move this to optimizations if we want, it may not be crucial to do something here.  

When payment status from the broker comes back as error, this happens:  

![image.png](https://images.zenhubusercontent.com/5a8c55194b5806bc2bc7ac81/8aa0ab8c-f408-484a-bc58-19df38d639be)   

Hopefully paymentStatus won't ever be error in prod but if it is we should display something.

Generic Error Screen: https://zpl.io/VqxPxL5

**Comment by rfornea** [comment]
Edmund says we can avoid the error in the console by returning something.  

If we have time we should put an error message on the screen.  @tfrench93 What should the message look like?  This happens when there's an error with user's payment.

**Comment by AaronVasquez** [comment]
@tfrench93 can you design a universal error alert box we can show when something unexpected happens?

**Comment by tfrench93** [comment]
@AaronVasquez There is currently an error page mocked up on Zeplin. Do you want something that is different than this and would act more like an overlay than a separate page? 

https://zpl.io/VqxPxL5

**Comment by AaronVasquez** [comment]
@tfrench93 that works. Eventually we might want to include error messages so users can self correct instead of having them contact support, but we can get to that later.
