### ISSUE TITLE
[Webinterface] Only allow certain characters in the handle

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/webinterface#161]
For handles, only allow the characters 0-9, a-z, A-Z, -, and _.

**Comment by CKH4** [comment]
How should the other characters be handled? Should they be completely stripped or replaced with something? A common way that this is handled is to replace space with "_". Should all invalid characters be treated this way, or only whitespace?

**Comment by rfornea** [comment]
Sorry I did not realize you had left a comment on this issue.
