### ISSUE TITLE
[All JS Repos] Standardize on static typing or eslint

### ISSUE THREAD

**Issue by AaronVasquez** [oysterprotocol/webinterface#177]
As our codebase and engineering team grows, we need more safety and documentation of our code. We should decide on standard tooling for all our JS Repos.

Tools to consider:
* ReasonML
* Typescript
* Flow
* ESLint (with a standardized config)

**Comment by MutsiMutsi** [comment]
@AaronVasquez Swagger

**Comment by MutsiMutsi** [comment]
@AaronVasquez Typescript + Jenkins + TSLint

**Comment by AaronVasquez** [comment]
We have decided on Typescript for static typing and will start off with the default TSLint config, which we may or may not tweak depending on our preferences.

See our doc for a detailed discussion:
https://docs.google.com/document/d/1uvjFlwcjTGR474BXAVmBb4sSNiz2ptd2rh4V_SIAyzo/edit?usp=sharing

**Comment by AaronVasquez** [comment]
This is being tracked with separate issues.
