### ISSUE TITLE
Configure TS lint and ensure its integrated with Travis

### ISSUE THREAD

**Issue by jfarago** [oysterprotocol/webinterface#187]
This may be covered during the build, just want to make sure we cover it.

Make sure this is configured on all three repos

- Webinterface
- Webnode
- Datamap-generator

**Comment by AaronVasquez** [comment]
Add precommit hook (add husky)

**Comment by mgpeng** [comment]
Hi,guys,   where can I find developing document for developing dapp on you project ?  I have a great idea
which is based on storage information in oyster blockchain.

**Comment by jfarago** [comment]
Is anyone currently working on this?

**Comment by jfarago** [comment]
Defaults are good and run with build, so there is no need for this story
