### ISSUE TITLE
Extract datamap generation into its own module.

### ISSUE THREAD

**Issue by AaronVasquez** [oysterprotocol/webinterface#93]
Both `webinterface` and `webnodes` have to generate a datamap. The logic will start to get more complex as we embed treasure into the datamap. It would be nice to share this code between the two repos.

Here is the current implementation:
https://github.com/oysterprotocol/webinterface/blob/master/src/utils/datamap.js

Note: This task is to just extract the current naive implementation we have before doing something more complex.

Also, I don't think we need the lodash dependency in this npm package we create.

**Comment by jfarago** [comment]
@AaronVasquez the datamap uses methods from the iota service and encryption utility. Should I recreate these methods in the new package or go another route? 

I imagine that more and more will get shared between these two projects. Should these other services/utility methods be abstracted into their own modules as well? I could replicate the methods for now and replace them later with a shared module.

**Comment by jfarago** [comment]
Nevermind, I talked to @rfornea. Gonna recreate for now.
