### ISSUE TITLE
[webinterface] Update UI to show payment status

### ISSUE THREAD

**Issue by AaronVasquez** [oysterprotocol/webinterface#97]
https://framer.cloud/ahwhK

>Retrieve UX
>https://drive.google.com/open?id=1fcY1qX1-19u-1UMLuXEjXWp1ZOAB3cqn

>Upload UX
>https://drive.google.com/open?id=1Xt7mgti_W52z6WbgvcONOGOc7hwoMeKx

**Comment by tfrench93** [comment]
@AaronVasquez 

The screens themselves are not going to change much. I am currently building a prototype using [Framer](https://framer.com/) to showcase the transitions and user flow of the desktop interface. Once the prototype is ready by the end of this week, I will post a link to the prototype on my Framer Cloud profile which all devs can interact with like it was a 'real' application per se. Will start working on the mobile interface after that is prepared.

**Comment by AaronVasquez** [comment]
https://framer.cloud/ahwhK

>Retrieve UX
>https://drive.google.com/open?id=1fcY1qX1-19u-1UMLuXEjXWp1ZOAB3cqn

>Upload UX
>https://drive.google.com/open?id=1Xt7mgti_W52z6WbgvcONOGOc7hwoMeKx

**Comment by AaronVasquez** [comment]
IMO, the payment status reflection is higher priority. The transitions look nice, but we can potentially push that to after the main net deadline if we're tight on time.

**Comment by tfrench93** [comment]
@AaronVasquez 

I agree. Functionality is more important than the animations, so the final transitions can be added later. I will link to the Framer prototype's CoffeeScript file here, which will be useful for determining the animation values. To my understanding, Framer's animations map nicely to Velocity.js.
